// Generated by gencpp from file robotnik_msgs/axis_record.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_AXIS_RECORD_H
#define ROBOTNIK_MSGS_MESSAGE_AXIS_RECORD_H

#include <ros/service_traits.h>


#include <robotnik_msgs/axis_recordRequest.h>
#include <robotnik_msgs/axis_recordResponse.h>


namespace robotnik_msgs
{

struct axis_record
{

typedef axis_recordRequest Request;
typedef axis_recordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct axis_record
} // namespace robotnik_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs::axis_record > {
  static const char* value()
  {
    return "2c515c47879efbb7383294f44d5255c1";
  }

  static const char* value(const ::robotnik_msgs::axis_record&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs::axis_record > {
  static const char* value()
  {
    return "robotnik_msgs/axis_record";
  }

  static const char* value(const ::robotnik_msgs::axis_record&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs::axis_recordRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs::axis_record >
template<>
struct MD5Sum< ::robotnik_msgs::axis_recordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs::axis_record >::value();
  }
  static const char* value(const ::robotnik_msgs::axis_recordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs::axis_recordRequest> should match
// service_traits::DataType< ::robotnik_msgs::axis_record >
template<>
struct DataType< ::robotnik_msgs::axis_recordRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs::axis_record >::value();
  }
  static const char* value(const ::robotnik_msgs::axis_recordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs::axis_recordResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs::axis_record >
template<>
struct MD5Sum< ::robotnik_msgs::axis_recordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs::axis_record >::value();
  }
  static const char* value(const ::robotnik_msgs::axis_recordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs::axis_recordResponse> should match
// service_traits::DataType< ::robotnik_msgs::axis_record >
template<>
struct DataType< ::robotnik_msgs::axis_recordResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs::axis_record >::value();
  }
  static const char* value(const ::robotnik_msgs::axis_recordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_AXIS_RECORD_H
