// Generated by gencpp from file robotnik_msgs/BoolArray.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_BOOLARRAY_H
#define ROBOTNIK_MSGS_MESSAGE_BOOLARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotnik_msgs
{
template <class ContainerAllocator>
struct BoolArray_
{
  typedef BoolArray_<ContainerAllocator> Type;

  BoolArray_()
    : data()  {
    }
  BoolArray_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::robotnik_msgs::BoolArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::BoolArray_<ContainerAllocator> const> ConstPtr;

}; // struct BoolArray_

typedef ::robotnik_msgs::BoolArray_<std::allocator<void> > BoolArray;

typedef boost::shared_ptr< ::robotnik_msgs::BoolArray > BoolArrayPtr;
typedef boost::shared_ptr< ::robotnik_msgs::BoolArray const> BoolArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_msgs::BoolArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_msgs::BoolArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotnik_msgs::BoolArray_<ContainerAllocator1> & lhs, const ::robotnik_msgs::BoolArray_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotnik_msgs::BoolArray_<ContainerAllocator1> & lhs, const ::robotnik_msgs::BoolArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotnik_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::BoolArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::BoolArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::BoolArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::BoolArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::BoolArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::BoolArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::BoolArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "403a16d9294b908e45c67a6f3c3a5b27";
  }

  static const char* value(const ::robotnik_msgs::BoolArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x403a16d9294b908eULL;
  static const uint64_t static_value2 = 0x45c67a6f3c3a5b27ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::BoolArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/BoolArray";
  }

  static const char* value(const ::robotnik_msgs::BoolArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::BoolArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] data\n"
;
  }

  static const char* value(const ::robotnik_msgs::BoolArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::BoolArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoolArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_msgs::BoolArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_msgs::BoolArray_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_BOOLARRAY_H
