// Generated by gencpp from file robotnik_msgs/InsertTaskResponse.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_INSERTTASKRESPONSE_H
#define ROBOTNIK_MSGS_MESSAGE_INSERTTASKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotnik_msgs
{
template <class ContainerAllocator>
struct InsertTaskResponse_
{
  typedef InsertTaskResponse_<ContainerAllocator> Type;

  InsertTaskResponse_()
    : success(false)
    , msg()  {
    }
  InsertTaskResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InsertTaskResponse_

typedef ::robotnik_msgs::InsertTaskResponse_<std::allocator<void> > InsertTaskResponse;

typedef boost::shared_ptr< ::robotnik_msgs::InsertTaskResponse > InsertTaskResponsePtr;
typedef boost::shared_ptr< ::robotnik_msgs::InsertTaskResponse const> InsertTaskResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator1> & lhs, const ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.msg == rhs.msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator1> & lhs, const ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotnik_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e835b04f93d0b30fd8cb71e0967a16db";
  }

  static const char* value(const ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe835b04f93d0b30fULL;
  static const uint64_t static_value2 = 0xd8cb71e0967a16dbULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/InsertTaskResponse";
  }

  static const char* value(const ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string msg\n"
"\n"
;
  }

  static const char* value(const ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InsertTaskResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_msgs::InsertTaskResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_INSERTTASKRESPONSE_H
