// Generated by gencpp from file robotnik_msgs/OdomManualCalibrationStatusStamped.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_ODOMMANUALCALIBRATIONSTATUSSTAMPED_H
#define ROBOTNIK_MSGS_MESSAGE_ODOMMANUALCALIBRATIONSTATUSSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <robotnik_msgs/OdomManualCalibrationStatus.h>

namespace robotnik_msgs
{
template <class ContainerAllocator>
struct OdomManualCalibrationStatusStamped_
{
  typedef OdomManualCalibrationStatusStamped_<ContainerAllocator> Type;

  OdomManualCalibrationStatusStamped_()
    : header()
    , status()  {
    }
  OdomManualCalibrationStatusStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::robotnik_msgs::OdomManualCalibrationStatus_<ContainerAllocator>  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator> const> ConstPtr;

}; // struct OdomManualCalibrationStatusStamped_

typedef ::robotnik_msgs::OdomManualCalibrationStatusStamped_<std::allocator<void> > OdomManualCalibrationStatusStamped;

typedef boost::shared_ptr< ::robotnik_msgs::OdomManualCalibrationStatusStamped > OdomManualCalibrationStatusStampedPtr;
typedef boost::shared_ptr< ::robotnik_msgs::OdomManualCalibrationStatusStamped const> OdomManualCalibrationStatusStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator1> & lhs, const ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator1> & lhs, const ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotnik_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "040580a8054e03204d303892affeca19";
  }

  static const char* value(const ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x040580a8054e0320ULL;
  static const uint64_t static_value2 = 0x4d303892affeca19ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/OdomManualCalibrationStatusStamped";
  }

  static const char* value(const ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"OdomManualCalibrationStatus status\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: robotnik_msgs/OdomManualCalibrationStatus\n"
"geometry_msgs/Pose odom_increment             # odometry increment since last reset\n"
"geometry_msgs/Pose real_increment             # real increment since last reset\n"
"\n"
"float32 linear_error            # linear error between odom and real since last reset\n"
"float32 angular_error           # angular error between odom and real since last reset\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OdomManualCalibrationStatusStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_msgs::OdomManualCalibrationStatusStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    s << std::endl;
    Printer< ::robotnik_msgs::OdomManualCalibrationStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_ODOMMANUALCALIBRATIONSTATUSSTAMPED_H
