// Generated by gencpp from file robotnik_msgs/ResetFromSubState.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_RESETFROMSUBSTATE_H
#define ROBOTNIK_MSGS_MESSAGE_RESETFROMSUBSTATE_H

#include <ros/service_traits.h>


#include <robotnik_msgs/ResetFromSubStateRequest.h>
#include <robotnik_msgs/ResetFromSubStateResponse.h>


namespace robotnik_msgs
{

struct ResetFromSubState
{

typedef ResetFromSubStateRequest Request;
typedef ResetFromSubStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetFromSubState
} // namespace robotnik_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs::ResetFromSubState > {
  static const char* value()
  {
    return "0692f61f0c43fdbd6f19facf658f4c39";
  }

  static const char* value(const ::robotnik_msgs::ResetFromSubState&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs::ResetFromSubState > {
  static const char* value()
  {
    return "robotnik_msgs/ResetFromSubState";
  }

  static const char* value(const ::robotnik_msgs::ResetFromSubState&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs::ResetFromSubStateRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs::ResetFromSubState >
template<>
struct MD5Sum< ::robotnik_msgs::ResetFromSubStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs::ResetFromSubState >::value();
  }
  static const char* value(const ::robotnik_msgs::ResetFromSubStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs::ResetFromSubStateRequest> should match
// service_traits::DataType< ::robotnik_msgs::ResetFromSubState >
template<>
struct DataType< ::robotnik_msgs::ResetFromSubStateRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs::ResetFromSubState >::value();
  }
  static const char* value(const ::robotnik_msgs::ResetFromSubStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs::ResetFromSubStateResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs::ResetFromSubState >
template<>
struct MD5Sum< ::robotnik_msgs::ResetFromSubStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs::ResetFromSubState >::value();
  }
  static const char* value(const ::robotnik_msgs::ResetFromSubStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs::ResetFromSubStateResponse> should match
// service_traits::DataType< ::robotnik_msgs::ResetFromSubState >
template<>
struct DataType< ::robotnik_msgs::ResetFromSubStateResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs::ResetFromSubState >::value();
  }
  static const char* value(const ::robotnik_msgs::ResetFromSubStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_RESETFROMSUBSTATE_H
