// Generated by gencpp from file robotnik_msgs/SetInt16.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_SETINT16_H
#define ROBOTNIK_MSGS_MESSAGE_SETINT16_H

#include <ros/service_traits.h>


#include <robotnik_msgs/SetInt16Request.h>
#include <robotnik_msgs/SetInt16Response.h>


namespace robotnik_msgs
{

struct SetInt16
{

typedef SetInt16Request Request;
typedef SetInt16Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt16
} // namespace robotnik_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs::SetInt16 > {
  static const char* value()
  {
    return "8f054c32edfcf21f89433b2b24f041c9";
  }

  static const char* value(const ::robotnik_msgs::SetInt16&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs::SetInt16 > {
  static const char* value()
  {
    return "robotnik_msgs/SetInt16";
  }

  static const char* value(const ::robotnik_msgs::SetInt16&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs::SetInt16Request> should match
// service_traits::MD5Sum< ::robotnik_msgs::SetInt16 >
template<>
struct MD5Sum< ::robotnik_msgs::SetInt16Request>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs::SetInt16 >::value();
  }
  static const char* value(const ::robotnik_msgs::SetInt16Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs::SetInt16Request> should match
// service_traits::DataType< ::robotnik_msgs::SetInt16 >
template<>
struct DataType< ::robotnik_msgs::SetInt16Request>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs::SetInt16 >::value();
  }
  static const char* value(const ::robotnik_msgs::SetInt16Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs::SetInt16Response> should match
// service_traits::MD5Sum< ::robotnik_msgs::SetInt16 >
template<>
struct MD5Sum< ::robotnik_msgs::SetInt16Response>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs::SetInt16 >::value();
  }
  static const char* value(const ::robotnik_msgs::SetInt16Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs::SetInt16Response> should match
// service_traits::DataType< ::robotnik_msgs::SetInt16 >
template<>
struct DataType< ::robotnik_msgs::SetInt16Response>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs::SetInt16 >::value();
  }
  static const char* value(const ::robotnik_msgs::SetInt16Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_SETINT16_H
