// Generated by gencpp from file robotnik_msgs/SetStringResponse.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_SETSTRINGRESPONSE_H
#define ROBOTNIK_MSGS_MESSAGE_SETSTRINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotnik_msgs/ReturnMessage.h>

namespace robotnik_msgs
{
template <class ContainerAllocator>
struct SetStringResponse_
{
  typedef SetStringResponse_<ContainerAllocator> Type;

  SetStringResponse_()
    : ret()  {
    }
  SetStringResponse_(const ContainerAllocator& _alloc)
    : ret(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robotnik_msgs::ReturnMessage_<ContainerAllocator>  _ret_type;
  _ret_type ret;





  typedef boost::shared_ptr< ::robotnik_msgs::SetStringResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::SetStringResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetStringResponse_

typedef ::robotnik_msgs::SetStringResponse_<std::allocator<void> > SetStringResponse;

typedef boost::shared_ptr< ::robotnik_msgs::SetStringResponse > SetStringResponsePtr;
typedef boost::shared_ptr< ::robotnik_msgs::SetStringResponse const> SetStringResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_msgs::SetStringResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_msgs::SetStringResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotnik_msgs::SetStringResponse_<ContainerAllocator1> & lhs, const ::robotnik_msgs::SetStringResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ret == rhs.ret;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotnik_msgs::SetStringResponse_<ContainerAllocator1> & lhs, const ::robotnik_msgs::SetStringResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotnik_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::SetStringResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::SetStringResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::SetStringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::SetStringResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::SetStringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::SetStringResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::SetStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1cc59476b1732f75af5b4512acb5adbe";
  }

  static const char* value(const ::robotnik_msgs::SetStringResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1cc59476b1732f75ULL;
  static const uint64_t static_value2 = 0xaf5b4512acb5adbeULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::SetStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/SetStringResponse";
  }

  static const char* value(const ::robotnik_msgs::SetStringResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::SetStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/ReturnMessage ret\n"
"\n"
"================================================================================\n"
"MSG: robotnik_msgs/ReturnMessage\n"
"bool success\n"
"string message\n"
"int16 code\n"
;
  }

  static const char* value(const ::robotnik_msgs::SetStringResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::SetStringResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetStringResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_msgs::SetStringResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_msgs::SetStringResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    s << std::endl;
    Printer< ::robotnik_msgs::ReturnMessage_<ContainerAllocator> >::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_SETSTRINGRESPONSE_H
