# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robotnik_msgs/MotorReferenceValueArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import robotnik_msgs.msg

class MotorReferenceValueArray(genpy.Message):
  _md5sum = "8397e49dd79671c43ebd06b3be44fa96"
  _type = "robotnik_msgs/MotorReferenceValueArray"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """MotorReferenceValue velocity
MotorReferenceValue position
MotorReferenceValue torque

================================================================================
MSG: robotnik_msgs/MotorReferenceValue
float32 target_value
int32 target_ref
float32 actual_value
int32 actual_ref
"""
  __slots__ = ['velocity','position','torque']
  _slot_types = ['robotnik_msgs/MotorReferenceValue','robotnik_msgs/MotorReferenceValue','robotnik_msgs/MotorReferenceValue']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       velocity,position,torque

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MotorReferenceValueArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.velocity is None:
        self.velocity = robotnik_msgs.msg.MotorReferenceValue()
      if self.position is None:
        self.position = robotnik_msgs.msg.MotorReferenceValue()
      if self.torque is None:
        self.torque = robotnik_msgs.msg.MotorReferenceValue()
    else:
      self.velocity = robotnik_msgs.msg.MotorReferenceValue()
      self.position = robotnik_msgs.msg.MotorReferenceValue()
      self.torque = robotnik_msgs.msg.MotorReferenceValue()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_fifififififi().pack(_x.velocity.target_value, _x.velocity.target_ref, _x.velocity.actual_value, _x.velocity.actual_ref, _x.position.target_value, _x.position.target_ref, _x.position.actual_value, _x.position.actual_ref, _x.torque.target_value, _x.torque.target_ref, _x.torque.actual_value, _x.torque.actual_ref))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.velocity is None:
        self.velocity = robotnik_msgs.msg.MotorReferenceValue()
      if self.position is None:
        self.position = robotnik_msgs.msg.MotorReferenceValue()
      if self.torque is None:
        self.torque = robotnik_msgs.msg.MotorReferenceValue()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.velocity.target_value, _x.velocity.target_ref, _x.velocity.actual_value, _x.velocity.actual_ref, _x.position.target_value, _x.position.target_ref, _x.position.actual_value, _x.position.actual_ref, _x.torque.target_value, _x.torque.target_ref, _x.torque.actual_value, _x.torque.actual_ref,) = _get_struct_fifififififi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_fifififififi().pack(_x.velocity.target_value, _x.velocity.target_ref, _x.velocity.actual_value, _x.velocity.actual_ref, _x.position.target_value, _x.position.target_ref, _x.position.actual_value, _x.position.actual_ref, _x.torque.target_value, _x.torque.target_ref, _x.torque.actual_value, _x.torque.actual_ref))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.velocity is None:
        self.velocity = robotnik_msgs.msg.MotorReferenceValue()
      if self.position is None:
        self.position = robotnik_msgs.msg.MotorReferenceValue()
      if self.torque is None:
        self.torque = robotnik_msgs.msg.MotorReferenceValue()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.velocity.target_value, _x.velocity.target_ref, _x.velocity.actual_value, _x.velocity.actual_ref, _x.position.target_value, _x.position.target_ref, _x.position.actual_value, _x.position.actual_ref, _x.torque.target_value, _x.torque.target_ref, _x.torque.actual_value, _x.torque.actual_ref,) = _get_struct_fifififififi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_fifififififi = None
def _get_struct_fifififififi():
    global _struct_fifififififi
    if _struct_fifififififi is None:
        _struct_fifififififi = struct.Struct("<fifififififi")
    return _struct_fifififififi
