(cl:in-package robotnik_msgs-msg)
(cl:export '(CAN_ID-VAL
          CAN_ID
          JOINT-VAL
          JOINT
          STATE-VAL
          STATE
          STATUS-VAL
          STATUS
          COMMUNICATIONSTATUS-VAL
          COMMUNICATIONSTATUS
          MODE_OF_OPERATION-VAL
          MODE_OF_OPERATION
          ACTIVESTATUSWORD-VAL
          ACTIVESTATUSWORD
          ACTIVEDRIVEFLAGS-VAL
          ACTIVEDRIVEFLAGS
          DIGITALOUTPUTS-VAL
          DIGITALOUTPUTS
          DIGITALINPUTS-VAL
          DIGITALINPUTS
          CURRENT-VAL
          CURRENT
          ANALOGINPUTS-VAL
          ANALOGINPUTS
          STATUSWORD-VAL
          STATUSWORD
          DRIVEFLAGS-VAL
          DRIVEFLAGS
))